config/routes.rb
Rails.application.routes.draw do

  resources :cities
  resources :speakers
  resources :phonemes
  resources :english_country_residences
  resources :native_languages
  resources :countries
  resources :states
  resources :cities
  resources :speakers
  devise_for :users
  get 'login/index'
  resources :home

  devise_scope :user do
    authenticated :user do
      root 'phonemes#index', as: "authenticated_root"
    end
    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticate_root
    end
  end

  root 'login#index'
end

app/models/english_country_residence.rb
class EnglishCountryResidence < ActiveRecord::Base
end

app/controllers/english_country_residences_controller.rb
class EnglishCountryResidencesController < ApplicationController
  before_action :set_english_country_residence, only: [:show, :edit, :update, :destroy]

  # GET /english_country_residences
  # GET /english_country_residences.json
  def index
    @english_country_residences = EnglishCountryResidence.all
  end

  # GET /english_country_residences/1
  # GET /english_country_residences/1.json
  def show
  end

  # GET /english_country_residences/new
  def new
    @english_country_residence = EnglishCountryResidence.new
  end

  # GET /english_country_residences/1/edit
  def edit
  end

  # POST /english_country_residences
  # POST /english_country_residences.json
  def create
    @english_country_residence = EnglishCountryResidence.new(english_country_residence_params)

    respond_to do |format|
      if @english_country_residence.save
        format.html { redirect_to @english_country_residence, notice: 'English country residence was successfully created.' }
        format.json { render :show, status: :created, location: @english_country_residence }
      else
        format.html { render :new }
        format.json { render json: @english_country_residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /english_country_residences/1
  # PATCH/PUT /english_country_residences/1.json
  def update
    respond_to do |format|
      if @english_country_residence.update(english_country_residence_params)
        format.html { redirect_to @english_country_residence, notice: 'English country residence was successfully updated.' }
        format.json { render :show, status: :ok, location: @english_country_residence }
      else
        format.html { render :edit }
        format.json { render json: @english_country_residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /english_country_residences/1
  # DELETE /english_country_residences/1.json
  def destroy
    @english_country_residence.destroy
    respond_to do |format|
      format.html { redirect_to english_country_residences_url, notice: 'English country residence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_english_country_residence
      @english_country_residence = EnglishCountryResidence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def english_country_residence_params
      params.require(:english_country_residence).permit(:name)
    end
end

app/helpers/english_country_residences_helper.rb
module EnglishCountryResidencesHelper
end

app/views/english_country_residences/_form.html.erb
<%= simple_form_for(@english_country_residence) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/english_country_residences/edit.html.erb
<h1>Editing English Country Residence</h1>

<%= render 'form' %>

<%= link_to 'Show', @english_country_residence %> |
<%= link_to 'Back', english_country_residences_path %>

app/views/english_country_residences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing English Country Residences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @english_country_residences.each do |english_country_residence| %>
      <tr>
        <td><%= english_country_residence.name %></td>
        <td><%= link_to 'Show', english_country_residence %></td>
        <td><%= link_to 'Edit', edit_english_country_residence_path(english_country_residence) %></td>
        <td><%= link_to 'Destroy', english_country_residence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New English country residence', new_english_country_residence_path %>

app/views/english_country_residences/new.html.erb
<h1>New English Country Residence</h1>

<%= render 'form' %>

<%= link_to 'Back', english_country_residences_path %>

app/views/english_country_residences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @english_country_residence.name %>
</p>

<%= link_to 'Edit', edit_english_country_residence_path(@english_country_residence) %> |
<%= link_to 'Back', english_country_residences_path %>