config/routes.rb
Rails.application.routes.draw do

  resources :cities
  resources :speakers
  resources :phonemes
  resources :english_country_residences
  resources :native_languages
  resources :countries
  resources :states
  resources :cities
  resources :speakers
  devise_for :users
  get 'login/index'
  resources :home

  devise_scope :user do
    authenticated :user do
      root 'phonemes#index', as: "authenticated_root"
    end
    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticate_root
    end
  end

  root 'login#index'
end

app/models/phoneme.rb
class Phoneme < ActiveRecord::Base
  belongs_to :speaker
end

app/controllers/phonemes_controller.rb
class PhonemesController < ApplicationController
  before_action :set_phoneme, only: [:show, :edit, :update, :destroy]

  # GET /phonemes
  # GET /phonemes.json
  def index
    @phonemes = Phoneme.all
  end

  # GET /phonemes/1
  # GET /phonemes/1.json
  def show
  end

  # GET /phonemes/new
  def new
    @phoneme = Phoneme.new
  end

  # GET /phonemes/1/edit
  def edit
  end

  # POST /phonemes
  # POST /phonemes.json
  def create
    @phoneme = Phoneme.new(phoneme_params)

    respond_to do |format|
      if @phoneme.save
        flash[:success] = 'Phoneme was successfully created.'
        format.html { redirect_to @phoneme }
        format.json { render :show, status: :created, location: @phoneme }
      else
        flash[:danger] = 'There was a problem creating the Phoneme.'
        format.html { render :new }
        format.json { render json: @phoneme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phonemes/1
  # PATCH/PUT /phonemes/1.json
  def update
    respond_to do |format|
      if @phoneme.update(phoneme_params)
        flash[:success] = 'Phoneme was successfully updated.'
        format.html { redirect_to @phoneme }
        format.json { render :show, status: :ok, location: @phoneme }
      else
        flash[:danger] = 'There was a problem updating the Phoneme.'
        format.html { render :edit }
        format.json { render json: @phoneme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phonemes/1
  # DELETE /phonemes/1.json
  def destroy
    @phoneme.destroy
    respond_to do |format|
      flash[:success] = 'Phoneme was successfully destroyed.'
      format.html { redirect_to phonemes_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_phoneme
    @phoneme = Phoneme.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def phoneme_params
    params.require(:phoneme).permit(:base, :actual, :diacritic, :sequence, :speaker_id)
  end
end

app/helpers/phonemes_helper.rb
module PhonemesHelper
end

app/views/phonemes/_form.html.erb
<%= simple_form_for(@phoneme) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :base, required: true %>
    <%= f.input :actual, required: true %>
    <%= f.input :diacritic, required: true %>
    <%= f.input :sequence, required: true %>
    <%= f.association :speaker, required: true %>
  </div>

  <div class="actions form-group">
    <%= f.submit %>
  </div>
  <!--TODO: Figure out how to make submit button look like this button:-->
  <!--<%= button_tag "Create Phoneme", type: 'submit', class: "btn btn-success" %>-->
<% end %>

app/views/phonemes/edit.html.erb
<h1>Editing Phoneme</h1>

<%= render 'form' %>

<%= link_to 'Show', @phoneme, class: 'btn btn-primary btn-xs' %> |
<%= link_to 'Back', phonemes_path, class: 'btn
        btn-danger btn-xs' %>

app/views/phonemes/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View Phoneme Data', phonemes_path %></li>
  <li><%= link_to 'Enter Phoneme Data', new_phoneme_path %></li>
  <li><%= link_to 'View Speakers', speakers_path %></li>
  <li><%= link_to 'Create Speaker', new_speaker_path %></li>
</ul>

<h1>Listing Phonemes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Base</th>
      <th>Actual</th>
      <th>Diacritic</th>
      <th>Sequence</th>
      <th>Speaker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phonemes.each do |phoneme| %>
      <tr>
        <td><%= phoneme.base %></td>
        <td><%= phoneme.actual %></td>
        <td><%= phoneme.diacritic %></td>
        <td><%= phoneme.sequence %></td>
        <td><%= phoneme.speaker.name %></td>
        <td><%= link_to 'Show', phoneme, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_phoneme_path(phoneme), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', phoneme, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn
        btn-danger btn-xs'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_phoneme_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Phoneme
<% end %>

app/views/phonemes/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View Phoneme Data', phonemes_path %></li>
  <li class="active"><%= link_to 'Enter Phoneme Data', new_phoneme_path %></li>
  <li><%= link_to 'View Speakers', speakers_path %></li>
  <li><%= link_to 'Create Speaker', new_speaker_path %></li>
</ul>

<h1>New Phoneme</h1>

<%= render 'form' %>

<%= link_to phonemes_path, class: "btn btn-danger btn-xs" do %>
  <i class="glyphicon glyphicon-arrow-left">Phonemes</i>
<% end %>

app/views/phonemes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Base:</strong>
  <%= @phoneme.base %>
</p>

<p>
  <strong>Actual:</strong>
  <%= @phoneme.actual %>
</p>

<p>
  <strong>Diacritic:</strong>
  <%= @phoneme.diacritic %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @phoneme.sequence %>
</p>

<p>
  <strong>Speaker:</strong>
  <%= @phoneme.speaker.name %>
</p>

<%= link_to 'Edit', edit_phoneme_path(@phoneme), class: 'btn btn-info btn-xs' %> |
<%= link_to 'Back', phonemes_path, class: 'btn btn-danger btn-xs' %>