config/routes.rb
Rails.application.routes.draw do

  resources :cities
  resources :speakers
  resources :phonemes
  resources :english_country_residences
  resources :native_languages
  resources :countries
  resources :states
  resources :cities
  resources :speakers
  devise_for :users
  get 'login/index'
  resources :home

  devise_scope :user do
    authenticated :user do
      root 'phonemes#index', as: "authenticated_root"
    end
    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticate_root
    end
  end

  root 'login#index'
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  SPEAKER_GENDERS  = [:male, :female]
  LEARNING_METHODS = [:acad, :nat]
  enum gender: SPEAKER_GENDERS
  enum learning_method: LEARNING_METHODS
  belongs_to :city
  belongs_to :state
  belongs_to :country
  belongs_to :native_language
  validates :gender, inclusion: {in: SPEAKER_GENDERS.map { |sg| sg.to_s }}
  validates :learning_method, inclusion: {in: LEARNING_METHODS.map { |l| l.to_s }}
  belongs_to :english_country_residence
  belongs_to :user
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  before_action :set_speaker, only: [:show, :edit, :update, :destroy]

  # GET /speakers
  # GET /speakers.json
  def index
    @speakers = Speaker.all
  end

  # GET /speakers/1
  # GET /speakers/1.json
  def show
  end

  # GET /speakers/new
  def new
    @speaker = Speaker.new
  end

  # GET /speakers/1/edit
  def edit
  end

  # POST /speakers
  # POST /speakers.json
  def create
    @speaker = Speaker.new(speaker_params)

    respond_to do |format|
      if @speaker.save
        flash[:success] = 'Speaker was successfully created.'
        format.html { redirect_to @speaker }
        format.json { render :show, status: :created, location: @speaker }
      else
        flash[:danger] = 'There was a problem creating the Speaker.'
        format.html { render :new }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speakers/1
  # PATCH/PUT /speakers/1.json
  def update
    respond_to do |format|
      if @speaker.update(speaker_params)
        flash[:success] = 'Speaker was successfully updated.'
        format.html { redirect_to @speaker }
        format.json { render :show, status: :ok, location: @speaker }
      else
        flash[:danger] = 'There was a problem updating the Speaker.'
        format.html { render :edit }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speakers/1
  # DELETE /speakers/1.json
  def destroy
    @speaker.destroy
    respond_to do |format|
      flash[:success] = 'Speaker was successfully destroyed.'
      format.html { redirect_to speakers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speaker
      @speaker = Speaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speaker_params
      params.require(:speaker).permit(:name, :city_id, :state_id, :country_id, :native_language_id, :other_languages, :age, :gender, :english_onset, :learning_method, :english_country_residence_id, :length_english_residence, :user_id)
    end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/speakers/_form.html.erb
<%= simple_form_for(@speaker) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.association :city, required: true %>
    <%= f.association :state %>
    <%= f.association :country, required: true %>
    <%= f.association :native_language, required: true %>
    <%= f.input :other_languages, label: '# Other Languages Known: ', required: true %>
    <%= f.input :age, required: true %>
    <%= f.input :gender, as: :select, collection: Speaker.genders.keys.to_a, required: true %>
    <%= f.input :english_onset, required: true %>
    <%= f.input :learning_method, as: :select, collection: Speaker.learning_methods.keys.to_a, required: true %>
    <%= f.association :english_country_residence %>
    <%= f.input :length_english_residence, required: true %>
  </div>

  <div class="actions form-group">
    <%= f.submit %>
  </div>
  <!--TODO: Figure out how to make submit button look like this button:-->
  <!--<%= button_tag "Create Speaker", type: 'submit', class: "btn btn-success" %>-->
<% end %>

app/views/speakers/edit.html.erb
<h1>Editing Speaker</h1>

<%= render 'form' %>

<%= link_to 'Show', @speaker, class: 'btn btn-primary btn-xs' %> |
<%= link_to 'Back', speakers_path, class: 'btn
        btn-danger btn-xs' %>

app/views/speakers/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View Phoneme Data', phonemes_path %></li>
  <li><%= link_to 'Enter Phoneme Data', new_phoneme_path %></li>
  <li class="active"><%= link_to 'View Speakers', speakers_path %></li>
  <li><%= link_to 'Create Speaker', new_speaker_path %></li>
</ul>

<h1>Listing Speakers</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Native language</th>
    <th>Other languages</th>
    <th>Age</th>
    <th>Gender</th>
    <th>English onset</th>
    <th>Learning method</th>
    <th>English country residence</th>
    <th>Length english residence</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @speakers.each do |speaker| %>
    <tr>
      <td><%= speaker.name %></td>
      <td><%= speaker.city.name %></td>
      <td><%= speaker.state.name %></td>
      <td><%= speaker.country.name %></td>
      <td><%= speaker.native_language.name %></td>
      <td><%= speaker.other_languages %></td>
      <td><%= speaker.age %></td>
      <td><%= speaker.gender %></td>
      <td><%= speaker.english_onset %></td>
      <td><%= speaker.learning_method %></td>
      <% if !speaker.english_country_residence.nil? %>
        <td><%= speaker.english_country_residence.name %></td>
      <% else %>
        <td><%= nil %></td>
      <% end %>
      <td><%= speaker.length_english_residence %></td>
      <td><%= link_to 'Show', speaker, class: 'btn btn-primary btn-xs' %></td>
      <td><%= link_to 'Edit', edit_speaker_path(speaker), class: 'btn btn-info btn-xs' %></td>
      <td><%= link_to 'Destroy', speaker, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn
        btn-danger btn-xs' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to new_speaker_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Speaker
<% end %>

app/views/speakers/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View Phoneme Data', phonemes_path %></li>
  <li><%= link_to 'Enter Phoneme Data', new_phoneme_path %></li>
  <li><%= link_to 'View Speakers', speakers_path %></li>
  <li class="active"><%= link_to 'Create Speaker', new_speaker_path %></li>
</ul>
<h1>New Speaker</h1>

<%= render 'form' %>

<%= link_to speakers_path, class: "btn btn-danger btn-xs" do %>
  <i class="glyphicon glyphicon-arrow-left">Speakers</i>
<% end %>

app/views/speakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @speaker.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @speaker.city.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @speaker.state.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @speaker.country.name %>
</p>

<p>
  <strong>Native language:</strong>
  <%= @speaker.native_language.name %>
</p>

<p>
  <strong>Other languages:</strong>
  <%= @speaker.other_languages %>
</p>

<p>
  <strong>Age:</strong>
  <%= @speaker.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @speaker.gender %>
</p>

<p>
  <strong>English onset:</strong>
  <%= @speaker.english_onset %>
</p>

<p>
  <strong>Learning method:</strong>
  <%= @speaker.learning_method %>
</p>

<% if !@speaker.english_country_residence.nil? %>
  <p>
    <strong>English country residence:</strong>
    <%= @speaker.english_country_residence.name %>
  </p>
<% end %>

<p>
  <strong>Length english residence:</strong>
  <%= @speaker.length_english_residence %>
</p>

<%= link_to 'Edit', edit_speaker_path(@speaker), class: 'btn btn-info btn-xs' %> |
<%= link_to 'Back', speakers_path, class: 'btn
        btn-danger btn-xs' %>